src/psl-make-dafsa
OS X doesn't follow [PEP 394](https://www.python.org/dev/peps/pep-0394/) and thus it doesn't have a `python2` binary. However, `python` is always Python 2 on OS X, and should be new enough to run `psl-make-dafsa` on the last five or so releases of OS X.
If this would break compatibility with other non-PEP-394 systems where `python` might be Python 3, another alternative might be to use `python2.7` specifically.
=> Change src/psl-make-dafsa shebang so it'll run on OS X

include/libpsl.h.in, src/psl.c, tests/test-is-public.c, tests/test-registrable-domain.c, tools/psl.c
When writing a wrapper around LibPSL in a different language it is
important that libpsl provide functions to free any memory that it
allocates. Without this, it is impossible to correctly free the memory
allocated by psl_str_to_utf8lower() function since in other languages
one may not have access to the same free() call from libc.
=> Add new function psl_free_string()

Makefile.am, configure.ac, msvc/Makefile.am, msvc/Makefile.vc, msvc/build-rules-msvc.mak, msvc/config-msvc.mak.in, msvc/config.h.win32.in, msvc/create-lists-msvc.mak, msvc/create-lists.bat, msvc/detectenv-msvc.mak, msvc/generate-msvc.mak, msvc/install-msvc.mak, msvc/libpsl-pc.py, msvc/pc_base.py, msvc/replace.py, src/Makefile.am, src/libpsl-srcs.mk
Hi,
This adds a set of NMake Makefiles and associated items for building libpsl using Visual Studio's NMake.  This also pulls out the source listings of libpsl into a separate Makefile snippet so that it can be included  by both the autotools Makefile.am and the NMake Makefiles for the build.
This attempts to make things modularized and this reuses items that have been used in the past for building items such as HarfBuzz (which I maintained the NMake Makefiles for it before it switched to CMake), due to the differences between GNUish Make and NMake.  Due to the complexity of building libidn/libidn2 with libunistring using Visual Studio, currently only builds using libicu as the runtime/builtin, or builds without runtime/builtin usage are supported with this set of NMake Makefiles.
With …
=> Add NMake Makefiles for Visual Studio builds

.travis.yml
When/If publicsuffix/list changes to NFC format, this commit
can be reverted.
=> Disable build without runtime for Travis

meson.build, src/meson.build, tests/meson.build
Hi,
As part of the steps to simplify the build system, this completes the support that is needed for libpsl to build on Windows using Meson, especially for Visual Studio builds.  After this gets merged, I think this will replace the NMake Makefiles that is used to build libpsl on Visual Studio.
=> Update the Meson build files so that things build on Windows

configure.ac, src/psl.c
At the moment the library requires Windows Vista or later, when working on Microsoft Windows.
I would like to suggest to not use inet_pton() on Windows and use the Winsock function that exists for the same purpose. The attached PR allows the library to run starting from Windows NT 2000. Actually the functions added for better compatibility with BSD are also based on Winsock, so I think that there are not pratical problems with this change.
Sincerely.
=> Fix older windows

tests/Makefile.am
The error message is as follows:
```
Making all in tests
make: don't know how to make ../list/public_suffix_list.dat. Stop
make: stopped in /usr/ports/works/usr/ports/dns/libpsl/work/libpsl-libpsl-0.21.0/tests
*** Error code 1
Stop.
```
PSL_FILE defaults to $(top_srcdir)/list/public_suffix_list.dat. When configured with --with-psl-file, the non-default PSL_FILE breaks the build in tests directory. Use $(PSL_FILE) instead of hardcoded $(top_srcdir)/list/public_suffix_list.dat to fix the build.
=> Fix build when configured with --with-psl-file

docs/libpsl/libpsl-docs.sgml
gtk-doc 1.30 no longer generates the file if the object tree is empty.
=> gtk-doc: do not include tree_index.sgml

src/Makefile.am, tests/Makefile.am
In an environment where only Python 3 is installed, configure.ac finds and sets
PYTHON=python3 correctly but src/psl-make-dafsa is called directly, so the hashbang of
`#!/usr/bin/env python` is used which doesn't exist.
Fix this by explicitly running $(PYTHON) when using the tool.
=> Makefile.am: use PYTHON when invoking psl-make-dafsa

README.MSVC.md, README.md, msvc/build-rules-msvc.mak, msvc/config-msvc.mak.in, msvc/create-lists-msvc.mak, msvc/detectenv-msvc.mak, msvc/generate-msvc.mak, msvc/install-msvc.mak
Hi,
This attempts to improve Visual Studio NMake builds by:
*  Fix test program builds, as new macro defines are needed to locate the generated dafsa data files.
*  Support Visual Studio 2019 better.
*  Separate intermediate PDBs during the build.
*  Differentiate builds between Visual Studio versions.
Since we also support Meson for Visual Studio builds, we also:
*  Add instructions on building libpsl on Visual Studio with NMake and Visual Studio (issue #145).
=> Improve Visual Studio builds Add instructions

meson.build, src/meson.build
This helps maintain ABI compatibility with the Autotools build so it's a drop-in replacement.
Previously we only outputted `libpsl.so`. Now we output:
```
libpsl.so -> libpsl.so.5
libpsl.so.5 -> libpsl.so.5.3.2
libpsl.so.5.3.2
```
Which is ABI-compatible with what autotools outputs:
```
libpsl.so -> libpsl.so.5.3.2
libpsl.so.5 -> libpsl.so.5.3.2
libpsl.so.5.3.2
```
=> meson: Use libtool library versioning, same as autotools

src/meson.build, tests/meson.build
Avoids using a python that may not exist in a python3 only distribution:
/usr/bin/env: ‘python’: No such file or directory
=> meson: run python script against the meson version of python

meson.build
This option has been available since 0.48, and we should use it
instead of only guessing based on buildtype.
=> meson: Use the b_vscrt option for selecting the CRT

src/meson.build
`find_program()` evaluates to `python psl-make-dafsa` on Windows, so running it with `python` evaluates to `python python psl-make-dafsa`, causing this error on Windows:
```
"c:/python38/python.exe" "python" "C:/projects/repos/libpsl/src/psl-make-dafsa" "--output-format=binary" "C:/projects/repos/libpsl/list/public_suffix_list.dat" "tests/psl.dafsa"
c:/python38/python.exe: can't open file 'python': [Errno 2] No such file or directory
```
Reported at https://gitlab.freedesktop.org/gstreamer/cerbero/-/issues/265.
=> meson: Fix running of psl-make-dafsa on Windows

tests/test-is-public-builtin.c
We in Platform.sh worked to remove `*.platform.sh` from PSL, and to replace it with `*.platformsh.site`, our other domain in the PSL. Now our MR to the official PSL would be blocked by failing tests specially due to these entries in `test-is-public-builtin`.
=> Update Platform.sh example in test_data

.travis.yml
Coveralls fails to report with a cryptic error:
```
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```
If I had to guess, I would say that this is [a consequence of the Sectigo certificate expiring on May 30th](https://access.redhat.com/articles/5117881).
=> Upgrade Ubuntu to fix the coveralls issue

src/meson.build
src/meson.build:19:0: ERROR: Unknown variable "libiconv".
=> meson: fix build

meson.build, src/meson.build
Build success on macOS and ubuntu.
=> Add libiconv dep to meson build again

meson.build, src/psl.c, tests/test-is-cookie-domain-acceptable.c, tools/psl.c
As reported at https://github.com/rockdaboot/libpsl/issues/173,
psl_is_cookie_domain_acceptable() doesn't work properly without
WSAStartup() on Windows.
Co-authored-by: gvanem@yahoo.no
=> Add WSAStartup() for Windows psl tool and tests.

fuzz/meson.build, meson.build, src/meson.build, tests/meson.build, tools/meson.build
ICU is a C++ library, event though it has C interface. This means that it depends on C++ standard library internally. When ICU is built as dynamic library we can link to it using C linker without issues because it is already linked to C+ standard library (I'm not sure how portable is this but it works). However, if ICU is built as static library, we must link to C++ standard library manually or use C++ linker, or else we will get linking errors.
This commit does this for Meson. I'm not sure how to do this properly for autotools (I was able to find [this](https://www.gnu.org/software/automake/manual/automake.html#How-the-Linker-is-Chosen) in the automake manual though).
=> Use C++ linker when building with libicu

fuzz/meson.build, src/meson.build, tests/meson.build, tools/meson.build
Automatically add PSL_STATIC (including to pkg-config metadata) when building Windows static library (this doesn't work with `--default-library both` and will print a warning).
Also fix linking of tests/tools executables when building Windows shared library by explicitly linking them with ws2_32.
=> meson: automatically add PSL_STATIC define when building Windows static library and fix tests/tools link errors

meson.build
In commit aa4909766c24c17bd1d9000ca419f6dc6b32c238 an option was modified and changed its type from a list of possible strings to a true/false value.
However, the build wasn't updated to correspond to that change, so it didn't logically work -- and Meson even threw a type error saying you cannot compare strings to booleans.
The actual change was basically "do not use this option anymore except to pass a macro to the source file and embed the data at all". So we can simply get rid of a bunch of complex dependency conditionals.
Fixes #185
=> meson: fix regression that made it impossible to build

src/psl.c
=> Fix "Although the value stored to 'pos' is used in the enclosing expression, the value is never actually read from 'pos'"

configure.ac
Ensures that calls to fopen() and stat() can handle largefiles.
=> Use AC_SYS_LARGEFILE

meson.build
Hi,
From the commit message:
<i>Since we are using Meson 0.60.0 or later, use CMake to help us find ICU, which is cleaner and more comprehensive, and allows us to use libicu_dep = depedency(...) even on Visual Studio, where CMake will find the appropriate ICU headers and libraries for us internally.</i>
<i>Sadly, due to peculiarities, we have to live with the warning that comes up as we needed to look for ICU in the older method instead of the recommended modules: ['ICU::uc'] method.</i>
=> meson: Clean up ICU dependency search

tools/psl.c
Hi,
From the commit message:
<i>localtime_r() is not available on Windows but a more-secure variant of localtime(), localtime_s() is provided on Windows.</i>
<i>Define localtime_r() on Windows as its arguments are reversed as compared to localetime_s(), to achive more or less the same purpose.</i>
=> tools/psl.c: Fix build on Windows

msvc/detectenv-msvc.mak
Hi,
Although we are supporting builds on Visual Studio via <strike>NMake</strike>Meson, I think it is a good idea to improve the NMake Makefiles as we still support that, by:
* Supporting ARM64 builds, with Visual Studio 2017 15.9.x or later.
* Distinguishing builds with Visual Studio 2019 and 2022.
=> Improve NMake Makefiles for ARM64 builds and Visual Studio 2022

meson.build, src/meson.build
libpsl.h can set up a PSL_API macro handling cross-platform symbol hiding/exporting, which depends on indicating that:
- we're currently building the library
- the compiler supports visibility attributes
This avoids leaking symbols and lets the compiler optimize calls.
=> meson: add support for symbol visibility

m4/visibility.m4
Without this, the gl_VISIBILITY macro in configure.ac doesn't work, which leaves some extra symbols exposed in some cases when building with autotools.
See https://github.com/rockdaboot/libpsl/issues/205
=> Add m4/visibility.m4 from gnulib 20230113+stable-1 (Closes: #205)

tests/meson.build
Breaks the build on MSYS2 when building inside a directory with a component starting with `U`, like `C:\Users`:
```
FAILED: tests/test-is-public-all.exe.p/test-is-public-all.c.obj
"cc"  "-Itests\test-is-public-all.exe.p" "-Itests" "-I..\tests" "-I." "-I.." "-Iinclude" "-I..\include" "-fdiagnostics-color=always" "-D_FILE_OFFSET_BITS=64" "-Wall" "-Winvalid-pch" "-O0" "-g" "-DHAVE_CONFIG_H" "-DSRCDIR=\"C:\\Users\\nirbheek\\tmp\\gstreamer\\subprojects\\libpsl\\tests\"" "-DPSL_FILE=\"C:/Users/nirbheek/tmp/gstreamer/subprojects/libpsl/list/public_suffix_list.dat\"" "-DPSL_TESTFILE=\"C:/Users/nirbheek/tmp/gstreamer/subprojects/libpsl/list/tests/tests.txt\"" "-DPSL_DAFSA=\"C:\\Users\\nirbheek\\tmp\\gstreamer\\subprojects\\libpsl\\builddir\\tests\\psl.dafsa\"" …
```
=> meson: Don't use paths with backslashes in defines

src/psl.c, tests/test-is-public-all.c, tests/test-is-public-builtin.c, tests/test-is-public.c, tests/test-registrable-domain.c
clang-cl errors on implicit functions. Needs the proper header included.
Fixes https://github.com/rockdaboot/libpsl/issues/216
=> fix compilation with clang-cl

configure.ac, src/psl.c
This change increases portability as some libc / compiler combinations doesn't know about strcasecmp().
=> Replace strcasecmp() with isUTF8()

configure.ac, meson.build, src/psl.c, tests/Makefile.am, tests/common.c, tests/common.h, tests/meson.build, tests/test-is-cookie-domain-acceptable.c, tests/test-is-public-all.c, tests/test-is-public-builtin.c, tests/test-is-public.c, tests/test-registrable-domain.c
`alloca()` needs special treatment for Windows and possibly other systems. The implementation also is compiler-specific. `alloca()` in general is considered "dangerous" (similar to variable-length arrays (VLAs)).
This PR drops the usage of `alloca()` for the aforementioned reasons.
=> Avoid alloca in libpsl and tests

meson.build
Don't look up the python module's find_installation() method. This is intended for detecting lots of information needed for compiling and installing python modules including the C-API interface to libpython, as well as site-packages layout information.
It's totally uninvolved with what we are doing, which is executing a script. For this, we just need any python program. Meson is written in python3, so we know in meson.build that we have that available -- which is also why meson guarantees that `find_program('python3')` always returns a valid python. Even if no python is installed on the system, meson will return the `meson.exe runpython` shim which runs the script using the copy of python bundled inside the redistributable meson Windows executable.
=> meson: simplify python3 detection

README.md
=> Add prerequisites for building with GNU autotools

configure.ac, m4/absolute-header.m4, m4/libunistring.m4, src/Makefile.am
Fixes #214
@TurtleWilly @rb07 Can you test this please?
It looks like it works for me:
```
$ ./configure --enable-runtime=libidn2 --with-libunistring-prefix=/tmp
...
$ make
...
$ ldd tests/test-is-public
linux-vdso.so.1 (0x00007ffd4179a000)
libpsl.so.5 => /home/tim/src/libpsl/src/.libs/libpsl.so.5 (0x00007f2440e2c000)
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2440c2d000)
libunistring.so.5 => /tmp/lib/libunistring.so.5 (0x00007f2440a70000)
libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f2440a3d000)
/lib64/ld-linux-x86-64.so.2 (0x00007f2440e46000)
```
=> Add configure flag --with-libunistring-prefix

libpsl.pc.in
Static libraries don't include dependency information, so when using pkg-config to find out how to link with a static library, the .pc file for that library has to specify what other libraries to link. Libs.private is like Libs, except it's only used when static linking. This fixes linking against a static libpsl using pkg-config.
The Meson-generated libpsl.pc just includes all of its dependent libraries in Libs, so doesn't require any additional fix.
=> Add Libs.private to autoconf libpsl.pc
